"use client";
// app/request/RequestManagerModal.tsx
import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabaseClient";
import { COMPANY } from "@/lib/config";
import {
  X,
  MessageCircle,
  ShieldCheck,
  Loader2,
  BellRing,
  MessageSquare,
} from "lucide-react";
import MasterDialog from "@/lib/components/MasterDialog";
import { decryptData } from "@/lib/crypto";

// 🔔 Notification Icon Component
export function RequestNotification({ deviceSn, pendingRequests, onClick }: any) {
  const hasRequest = pendingRequests?.some((r: any) =>
    String(r.device_sn).trim().toLowerCase() === String(deviceSn).trim().toLowerCase()
  );
  if (!hasRequest) return null;
  return (
    <button
      onClick={(e) => { e.stopPropagation(); onClick(); }}
      className="absolute left-6 top-6 text-red-600 hover:scale-110 active:scale-90 transition-all z-[110] p-1 bg-white/80 backdrop-blur-md rounded-full shadow-lg border border-red-100"
    >
      <div className="relative">
        <BellRing size={22} className="animate-pulse" />
        <span className="absolute -top-1 -right-1 flex h-3 w-3">
          <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-red-400 opacity-75"></span>
          <span className="relative inline-flex rounded-full h-3 w-3 bg-red-600 border border-white"></span>
        </span>
      </div>
    </button>
  );
}

export default function RequestManagerModal({ isOpen, onClose, onRefresh, filterSn }: any) {
  const [requests, setRequests] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [dialog, setDialog] = useState({ isOpen: false, title: "", message: "", type: "info" as any });

  useEffect(() => {
    if (isOpen) {
      document.body.style.overflow = "hidden";
      fetchRequests();
    } else {
      document.body.style.overflow = "unset";
    }
    return () => { document.body.style.overflow = "unset"; };
  }, [isOpen, filterSn]);

  const fetchRequests = async () => {
    setLoading(true);
    try {
      let query = supabase.from("requests").select("*").eq("status", "pending");
      if (filterSn) query = query.eq("device_sn", filterSn.trim());
      const { data } = await query.order("created_at", { ascending: false });

      if (data?.length) {
        const { data: devData } = await supabase.from("devices").select("device_sn, user_pass, user_name").in("device_sn", data.map((r: any) => r.device_sn));
        setRequests(data.map((req: any) => ({
          ...req,
          deviceDetails: devData?.find((d: any) => String(d.device_sn).trim().toLowerCase() === String(req.device_sn).trim().toLowerCase())
        })));
      } else { setRequests([]); }
    } catch (err) { console.error(err); } finally { setLoading(false); }
  };

  const generatePortalId = (sn: string) => {
    if (!sn || sn.length < 8) return "ME_ADMIN";
    return `ME_${sn.slice(-8).slice(0, 4).toLowerCase()}`;
  };

  // 🚩 SAFARI & CHROME COMPATIBLE DISPATCH MASTER LOGIC
  const handleAction = async (req: any) => {
    const rawPass = req.deviceDetails?.user_pass || req.user_pass || "";
    const finalPass = decryptData(rawPass); 
    
    const portalId = generatePortalId(req.device_sn);

    // 🚩 Message Formatting
    const msg = `*🔐 CCTV ACCESS DETAILS*

📍 *Site:* ${req.site_name}
🆔 *Portal ID:* ${portalId}
👤 *User Name:* user
🛡️ *User Pass:* ${finalPass}

_Generated by ${COMPANY?.name || "MODERN ENTERPRISES"}_`;
    
    const mobile = (req.mobile || "").replace(/\D/g, "");
    const finalMobile = mobile.startsWith("91") ? mobile : `91${mobile}`;
    
    const waUrl = `https://api.whatsapp.com/send?phone=${finalMobile}&text=${encodeURIComponent(msg)}`;

    try {
      // 📝 Background DB Update: Pending -> Done
      const { error } = await supabase
        .from("requests")
        .update({ status: "done" })
        .eq("id", req.id);

      if (!error) {
        fetchRequests(); 
        onRefresh();
      }

      // 🚀 WhatsApp Dispatch
      window.open(waUrl, '_blank', 'noopener,noreferrer');

      if (filterSn) onClose();
    } catch (err) {
      console.error("Dispatch Error:", err);
      window.open(waUrl, '_blank');
    }
  };

  if (!isOpen) return null;

  return (
    <>
      {/* FULL SCREEN MODAL */}
      <div className="fixed inset-0 z-[99999] flex items-end sm:items-center justify-center bg-slate-900/90 backdrop-blur-md animate-in fade-in duration-300" style={{ height: '100dvh' }}>
        
        <div className="w-full max-w-2xl bg-[#f8fafc] rounded-t-[45px] sm:rounded-[45px] flex flex-col overflow-hidden relative shadow-2xl" style={{ maxHeight: 'calc(100dvh - 20px)' }}>
          
          <div className="h-2 w-full bg-gradient-to-r from-blue-600 via-blue-500 to-emerald-400 shrink-0"></div>

          {/* HEADER */}
          <div className="p-6 border-b border-slate-100 flex justify-between items-center bg-white shrink-0 text-left">
            <div>
              <h2 className="text-lg font-[1000] text-slate-900 uppercase italic flex items-center gap-2 tracking-tighter leading-none">
                <ShieldCheck className="text-blue-600" size={22} /> Requests Manager
              </h2>
              <p className="text-[9px] font-black text-slate-400 uppercase tracking-[2px] mt-1.5">Live Requests</p>
            </div>
            <button onClick={onClose} className="p-3 bg-slate-50 hover:bg-slate-100 rounded-2xl active:scale-90 border transition-all text-slate-400 shadow-inner">
              <X size={20} strokeWidth={3} />
            </button>
          </div>

          {/* CONTENT LIST */}
          <div className="p-4 overflow-y-auto space-y-4 bg-slate-50/50 flex-1 overscroll-contain pb-32 text-left">
            {loading ? (
              <div className="py-24 flex flex-col items-center gap-4">
                <Loader2 className="animate-spin text-blue-600" size={36} />
                <p className="text-[10px] font-black text-slate-400 uppercase tracking-[5px] italic">Syncing Live Node...</p>
              </div>
            ) : requests.length === 0 ? (
              <div className="py-32 text-center opacity-20 flex flex-col items-center gap-5 italic font-black">
                <BellRing size={50} />
                <p className="text-xs uppercase tracking-[6px]">All Clear - No Tasks</p>
              </div>
            ) : (
              requests.map((req: any) => (
                <div key={req.id} className="group relative p-6 rounded-[35px] border border-slate-200 bg-white shadow-sm hover:border-blue-200 transition-all text-left overflow-hidden border-l-[3px] border-l-blue-600">
                  <div className="flex items-start justify-between gap-4 mb-5">
                    <h3 className="text-lg font-[1000] text-slate-900 uppercase italic leading-tight tracking-tight">{req.site_name}</h3>
                    <span className="text-[10px] font-black text-slate-500 bg-slate-50 px-3 py-1 rounded-xl border border-slate-100 uppercase italic">ID: {req.device_sn.slice(-8).toUpperCase()}</span>
                  </div>

                  {req.message && (
                    <div className="flex items-start gap-4 bg-blue-50/50 p-4 rounded-[20px] border border-blue-100 mb-5">
                      <MessageSquare size={18} className="text-blue-600 shrink-0 mt-0.5" />
                      <p className="text-[13px] font-bold text-blue-900 leading-snug italic">"{req.message}"</p>
                    </div>
                  )}

                  <div className="flex flex-wrap items-center justify-between gap-6 pt-6 border-t border-slate-50">
                    <div className="flex items-center gap-6">
                      <div className="flex flex-col pr-8 border-r-2 border-slate-100">
                        <span className="text-[9px] font-black text-blue-500 uppercase tracking-[2px] leading-none">Portal ID</span>
                        <span className="text-sm font-[1000] text-slate-800 mt-2 uppercase italic tracking-tighter">{generatePortalId(req.device_sn)}</span>
                      </div>
                      <div className="flex flex-col">
                        <span className="text-[9px] font-black text-slate-400 uppercase tracking-[2px] leading-none">WhatsApp</span>
                        <span className="text-sm font-black text-slate-800 mt-2 italic tracking-tighter">{req.mobile}</span>
                      </div>
                    </div>
                    <button onClick={() => handleAction(req)} className="w-full sm:w-auto bg-blue-600 text-white px-10 py-4.5 rounded-[30px] flex items-center justify-center gap-3 text-[12px] font-[1000] uppercase tracking-widest shadow-2xl active:scale-95 transition-all border-b-[5px] border-blue-900 italic">
                      <MessageCircle size={20}/> Dispatch Access
                    </button>
                  </div>
                </div>
              ))
            )}
          </div>
        </div>
      </div>

      <MasterDialog 
        isOpen={dialog.isOpen} 
        onClose={() => setDialog(p => ({ ...p, isOpen: false }))} 
        onConfirm={() => setDialog(p => ({ ...p, isOpen: false }))} 
        title={dialog.title} 
        message={dialog.message} 
        type={dialog.type} 
      />
    </>
  );
}