import { NextResponse } from "next/server";
import { supabase } from "@/lib/supabaseClient";
import { Resend } from "resend";

const resend = new Resend(process.env.RESEND_API_KEY);

export async function POST(req: Request) {
  try {
    const { mobile, device_id } = await req.json();

    // 🔍 UPDATE 1: Query mein 'sn' ki jagah 'device_sn' use kiya
    const { data: device, error: fetchError } = await supabase
      .from("devices")
      .select("*")
      .eq("device_sn", device_id) // ✅ Fixed: Matching with new column name
      .single();

    if (fetchError || !device) {
      console.error("Database Fetch Error:", fetchError);
      return NextResponse.json({ success: false, error: "Device not found" }, { status: 404 });
    }

    const requestDate = new Date().toLocaleString("en-IN", {
      timeZone: "Asia/Kolkata",
      day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit", hour12: true,
    });

    const cleanMobile = mobile.replace(/\D/g, "");
    const techMobile = cleanMobile.startsWith("91") ? cleanMobile : `91${cleanMobile}`;
    
    // ✨ Message formatting remains clean and professional
    const rawMessage = 
      `*🔐 CCTV ACCESS DETAILS*\n\n` +
      `📍 *Site:* ${device.site_name}\n` +
      `👤 *User Name:* user\n` +
      `🛡️ *User Pass:* ${device.user_pass}\n` +
      `🌐 *IP:* ${device.ip_address || 'N/A'}\n\n` +
      `_Generated by MODERN ENTERPRISES Security Portal_`;

    const encodedMessage = encodeURIComponent(rawMessage);
    const techWaLink = `https://api.whatsapp.com/send?phone=${techMobile}&text=${encodedMessage}`;

    // 📧 Resend Email Logic
    await resend.emails.send({
      from: "CCTV Portal <onboarding@resend.dev>",
      to: "wazahul@gmail.com",
      subject: `🚨 REQUEST: ${device.site_name} | ${requestDate}`,
      html: `
        <div style="font-family: sans-serif; border: 1px solid #e2e8f0; padding: 25px; border-radius: 24px; max-width: 480px; background: #ffffff;">
          <div style="text-align: center; margin-bottom: 20px;">
            <h2 style="color: #0f172a; margin: 0; font-size: 20px;">🔐 Password Request</h2>
            <p style="color: #64748b; font-size: 13px;">New alert from ${device.site_name}</p>
          </div>

          <div style="background: #f8fafc; padding: 20px; border-radius: 18px; border: 1px solid #f1f5f9; margin-bottom: 25px;">
            <p style="margin: 5px 0;"><b>📍 Site:</b> ${device.site_name}</p>
            <p style="margin: 5px 0;"><b>🔢 SN:</b> ${device.device_sn}</p> <p style="margin: 5px 0;"><b>📱 User:</b> ${mobile}</p>
            <hr style="border: none; border-top: 1px solid #e2e8f0; margin: 15px 0;" />
            <p style="margin: 5px 0; color: #2563eb;"><b>USER NAME:</b> user</p>
            <p style="margin: 5px 0; color: #2563eb;"><b>USER PASS:</b> ${device.user_pass}</p>
          </div>

          <a href="${techWaLink}" 
             target="_blank"
             style="display: block; text-align: center; background: #22c55e; color: white; padding: 18px; border-radius: 20px; text-decoration: none; font-weight: bold; font-size: 16px; box-shadow: 0 10px 15px -3px rgba(34, 197, 94, 0.2);">
             💬 SEND VIA WHATSAPP
          </a>

          <p style="text-align: center; font-size: 10px; color: #cbd5e1; margin-top: 25px; font-weight: bold; text-transform: uppercase; letter-spacing: 2px;">
            System Engine 2026
          </p>
        </div>
      `,
    });

    return NextResponse.json({ success: true });

  } catch (err) {
    console.error("API Error:", err);
    return NextResponse.json({ success: false }, { status: 500 });
  }
}