import { NextResponse } from "next/server";
import { supabase } from "@/lib/supabaseClient";
import { COMPANY } from "@/lib/config";
import { Resend } from "resend";
import { decryptData } from "@/lib/crypto"; // 🚩 Zaroori: Decryption ke liye

const resend = new Resend(process.env.RESEND_API_KEY);

export async function POST(req: Request) {
  try {
    const { mobile, device_id ,message} = await req.json();

    // 1. Database se Device ka data nikalo
    const { data: device, error: fetchError } = await supabase
      .from("devices")
      .select("*")
      .eq("device_sn", device_id)
      .single();

    if (fetchError || !device) {
      return NextResponse.json({ success: false, error: "Node not found" }, { status: 404 });
    }

    // 2. 🔓 PASSWORD DECRYPTION (Asli kaam yahan ho raha hai)
    // Agar DB mein encrypted hai toh saaf ho jayega, agar plain hai toh waisa hi rahega
    const finalPass = decryptData(device.user_pass);

    // 3. 🆔 PORTAL ID GENERATOR
    const generatePortalId = (sn: string) => {
      if (!sn || sn.length < 8) return "ME_ADMIN";
      return `ME_${sn.slice(-8).slice(0, 4).toLowerCase()}`;
    };
    const portalId = generatePortalId(device.device_sn);

    // 4. 🕒 Indian Timestamp
    const requestTimestamp = new Date().toLocaleString("en-IN", {
      timeZone: "Asia/Kolkata",
      day: "2-digit", month: "short", year: "numeric", 
      hour: "2-digit", minute: "2-digit", hour12: true,
    });

    // 5. 📱 WhatsApp Link Formatting (Admin ke liye)
    const cleanMobile = mobile.replace(/\D/g, "");
    const techMobile = cleanMobile.startsWith("91") ? cleanMobile : `91${cleanMobile}`;
    
    const rawMessage = 
      `*🔐 CCTV ACCESS DETAILS*\n\n` +
      `📍 *Site:* ${device.site_name}\n` +
      `🆔 *Portal ID:* ${portalId}\n` +
      `👤 *User Name:* user\n` +
      `🛡️ *User Pass:* ${finalPass}\n\n` + // ✅ Ab yahan saaf password jayega
      `_Generated by ${COMPANY?.name || "Modern Enterprises"}_`;

    const encodedMessage = encodeURIComponent(rawMessage);
    const techWaLink = `https://api.whatsapp.com/send?phone=${techMobile}&text=${encodedMessage}`;

    // 6. 📧 EMAIL DISPATCH (To Admin)
    await resend.emails.send({
  from: "CCTV Portal <onboarding@resend.dev>",
  to: "wazahul@gmail.com",
  subject: `🚨 REQUEST: ${device.site_name} | ${requestTimestamp}`,
  html: `
    <div style="font-family: sans-serif; border: 1px solid #e2e8f0; padding: 30px; border-radius: 24px; max-width: 500px; background: #ffffff; color: #0f172a;">
      <h2 style="text-align: center; margin-bottom: 20px; font-weight: 900; letter-spacing: -1px; text-transform: uppercase; font-style: italic;">🔐 Access Request</h2>
      
      <div style="background: #f8fafc; padding: 20px; border-radius: 18px; border: 1px solid #f1f5f9; margin-bottom: 25px; line-height: 1.6;">
        <p style="margin: 5px 0; font-size: 14px;"><b>📍 Site:</b> ${device.site_name}</p>
        <p style="margin: 5px 0; font-size: 14px;"><b>🆔 Portal ID:</b> ${portalId}</p>
        <p style="margin: 5px 0; font-size: 14px;"><b>📱 User Mobile:</b> ${mobile}</p>
        
        <div style="margin-top: 15px; padding-top: 15px; border-top: 2px dashed #e2e8f0;">
          <p style="margin: 0; font-size: 11px; text-transform: uppercase; letter-spacing: 2px; color: #94a3b8; font-weight: bold;">User Message:</p>
          <p style="margin: 5px 0; font-size: 15px; color: #1e293b; font-weight: 600; font-style: italic;">
            "${message || "Password Request"}"
          </p>
        </div>

        <p style="margin: 15px 0 0 0; color: #64748b; font-size: 10px; font-weight: bold; text-transform: uppercase; letter-spacing: 1px;">⏰ Requested At: ${requestTimestamp}</p>
      </div>

      <a href="${techWaLink}" style="display: block; text-align: center; background: #2563eb; color: white; padding: 20px; border-radius: 20px; text-decoration: none; font-weight: bold; text-transform: uppercase; letter-spacing: 1px; box-shadow: 0 4px 12px rgba(37, 99, 235, 0.2);">
         Process via WhatsApp
      </a>

      <p style="text-align: center; font-size: 10px; color: #cbd5e1; margin-top: 30px; letter-spacing: 3px; font-weight: bold; text-transform: uppercase;">
        ${COMPANY?.name || "Modern Enterprises"} | ${COMPANY?.branding?.copyRightYear || "2026"}
      </p>
    </div>
  `,
});

    return NextResponse.json({ success: true });

  } catch (err: any) {
    console.error("Email API Error:", err.message);
    return NextResponse.json({ success: false, error: err.message }, { status: 500 });
  }
}