import { NextResponse } from "next/server";
import { supabase } from "@/lib/supabaseClient";
import { Resend } from "resend";

const resend = new Resend(process.env.RESEND_API_KEY);

export async function POST(req: Request) {
  try {
    const { mobile, device_id } = await req.json();

    const { data: device, error: fetchError } = await supabase
      .from("devices")
      .select("*")
      .eq("device_sn", device_id)
      .single();

    if (fetchError || !device) {
      return NextResponse.json({ success: false, error: "Node not found" }, { status: 404 });
    }

    // 🛠️ PORTAL ID GENERATOR (As per your logic)
    const generatePortalId = (sn: string) => {
      if (!sn || sn.length < 8) return "ME_ADMIN";
      // Last 8 characters uthaye, phir usme se pehle 4 liye aur lowercase kiya
      return `ME_${sn.slice(-8).slice(0, 4).toLowerCase()}`;
    };

    const portalId = generatePortalId(device.device_sn);

    // 🕒 Precise Timestamp for Email
    const requestTimestamp = new Date().toLocaleString("en-IN", {
      timeZone: "Asia/Kolkata",
      day: "2-digit", month: "short", year: "numeric", 
      hour: "2-digit", minute: "2-digit", hour12: true,
    });

    const cleanMobile = mobile.replace(/\D/g, "");
    const techMobile = cleanMobile.startsWith("91") ? cleanMobile : `91${cleanMobile}`;
    
    // ✨ WHATSAPP MESSAGE (Portal ID Added)
    const rawMessage = 
      `*🔐 CCTV ACCESS DETAILS*\n\n` +
      `📍 *Site:* ${device.site_name}\n` +
      `🆔 *Portal ID:* ${portalId}\n` +
      `👤 *User Name:* user\n` +
      `🛡️ *User Pass:* ${device.user_pass}\n\n` +
      `_Generated by MODERN ENTERPRISES_`;

    const encodedMessage = encodeURIComponent(rawMessage);
    const techWaLink = `https://api.whatsapp.com/send?phone=${techMobile}&text=${encodedMessage}`;

    // 📧 EMAIL DISPATCH
    await resend.emails.send({
      from: "CCTV Portal <onboarding@resend.dev>",
      to: "wazahul@gmail.com",
      subject: `🚨 REQUEST: ${device.site_name} | ${requestTimestamp}`,
      html: `
        <div style="font-family: sans-serif; border: 1px solid #e2e8f0; padding: 30px; border-radius: 24px; max-width: 500px; background: #ffffff;">
          <h2 style="color: #0f172a; text-align: center; margin-bottom: 20px;">🔐 Access Request</h2>
          <div style="background: #f8fafc; padding: 20px; border-radius: 18px; border: 1px solid #f1f5f9; margin-bottom: 25px; line-height: 1.6;">
            <p style="margin: 5px 0;"><b>📍 Site:</b> ${device.site_name}</p>
            <p style="margin: 5px 0;"><b>🆔 Portal ID:</b> ${portalId}</p>
            <p style="margin: 5px 0;"><b>📱 User Mobile:</b> ${mobile}</p>
            <p style="margin: 5px 0; color: #64748b;"><b>⏰ Time:</b> ${requestTimestamp}</p>
          </div>
          <a href="${techWaLink}" style="display: block; text-align: center; background: #2563eb; color: white; padding: 20px; border-radius: 20px; text-decoration: none; font-weight: bold; text-transform: uppercase; letter-spacing: 1px;">
             Process via WhatsApp
          </a>
          <p style="text-align: center; font-size: 10px; color: #cbd5e1; margin-top: 30px; letter-spacing: 3px; font-weight: bold;">
            MODERN ENTERPRISES 2026
          </p>
        </div>
      `,
    });

    return NextResponse.json({ success: true });

  } catch (err: any) {
    return NextResponse.json({ success: false, error: err.message }, { status: 500 });
  }
}